### PR TITLE
add nodejs16.x runtime

### PR DESCRIPTION
**Pull request by TastefulElk**
add support for the newly released nodejs16.x Lambda runtime

### CODE REVIEW

**Comment by TastefulElk** [comment]
@pavelvlasov leaving a friendly bump here if you have time to take a look at this 🙂

**Comment by mishabruml** [comment]
bump

**Comment by OrRosenblatt** [comment]
Friendly request to bump :)

**Review by ChrisClark13 — APPROVED** [review]

**Review by Christop406 — APPROVED** [review]

**Comment by pavelvlasov** [comment]
thanks for the contribution @TastefulElk! Runtimes was updated by another PR and should be available in the next version. I'll close this PR.

Unfortunately, I don't have much time these days to look after the plugin, so sometimes things are getting slower than expected.

**Pull request closed without merging**
